name: Pipeline de CI - EncomendasSmart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm'

    - name: Mensagem de Início
      run: echo "Iniciando o processo de Integração Contínua para o projeto EncomendasSmart..."

    - name: Instalar dependências
      run: npm install

    - name: Validar Build do Projeto
      run: npm run build -- --configuration production

    - name: Listar arquivos gerados
      run: |
        echo "Listando arquivos do diretório de build:"
        ls -R dist/ || echo "Diretório dist não encontrado. Verifique o log do build."
